baseURL = "/"
languageCode = "en-uk"
title = "Dr Anna Krystalli | r-rse"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/r-rse-logo.svg"
    mobile_height = "80px"
    mobile_width = "80px"
    desktop = "images/r-rse-logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "r-rse services"

  [params.homepage_meta_tags]
    meta_description = "Dr. Anna Krystalli - Research Software Engineering Services in R."
    meta_og_title = "Dr Anna Krystalli | r-rse"
    meta_og_type = "website"
    meta_og_url = "https://r-rse.eu"
    meta_og_image = "https://www.r-rse.eu/images/summary-card.png"
    meta_og_description = "Dr. Anna Krystalli - Research Software Engineering Services in R."
    meta_twitter_card = "summary"
    meta_twitter_site = "@annakrystalli"
    meta_twitter_creator = "@annakrystalli"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "CV"
    url = "docs/full-cv.pdf"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
